### ISSUE TITLE
More detailed Getting Started with Guide for beginners please.

### ISSUE THREAD

**Issue by stardust-96** [chenhaoxing/DiffusionInst#7]
Hey, I'm a beginner in CV and plan to evaluate your model over a dataset I collected. But, firstly I want to run its demo. Can you please elaborate more on using Model Zoo in that guide? I'm getting the following error. How can I get the checkpoint file?
Note: It will be helping if you can also add some details on how to train it on a custom dataset.

`Traceback (most recent call last):
  File "/content/DiffusionInst/demo.py", line 106, in <module>
    demo = VisualizationDemo(cfg)
  File "/content/DiffusionInst/diffusioninst/predictor.py", line 34, in __init__
    self.predictor = DefaultPredictor(cfg)
  File "/content/detectron2/detectron2/engine/defaults.py", line 288, in __init__
    checkpointer.load(cfg.MODEL.WEIGHTS)
  File "/content/detectron2/detectron2/checkpoint/detection_checkpoint.py", line 62, in load
    ret = super().load(path, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/fvcore/common/checkpoint.py", line 153, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint diffinst_coco_res50.pth not found!`

**Comment by zhangxgu** [comment]
@leo96code 
Hi, demo.py is utilized to visualize instance segmentation result on COCO. You can not directly run demo.py without training the model first The trained weights will be uploaded in a few weeks, since we are very busy these days at the end of this year. 
And for beginners, I highly recommend you to run some demos of Detectron2 or MMdetection.
